export const responseType = {
	Question: "q",
	Image: "i",
};

export const questions = [
	{
		index: 0,
		type: responseType.Question,
		question: "Frequently Asked Questions",
		response: [1, 2, 3, 4, 5, 6, 81],
		answer: "",
	},
	// Categories
	{
		index: 1,
		type: responseType.Question,
		question: "Amenities & Facilities",
		response: [7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
		answer: "",
	},
	{
		index: 2,
		type: responseType.Question,
		question: "Booking",
		response: [17, 18, 19, 20, 21],
		answer: "",
	},
	{
		index: 3,
		type: responseType.Question,
		question: "Technical Support",
		response: [22, 23, 24, 25, 26, 27, 28],
		answer: "",
	},
	{
		index: 4,
		type: responseType.Question,
		question: "Co-Teaching",
		response: [30, 31, 32],
		answer: "",
	},
	{
		index: 5,
		type: responseType.Question,
		question: "General Information",
		response: [33, 34, 35, 36],
		answer: "",
	},
	{
		index: 6,
		type: responseType.Question,
		question: "Package",
		response: [37, 38],
		answer: "",
	},
	{
		index: 81,
		type: responseType.Question,
		question: "Contact Us",
		response: [82, 83, 84, 85],
		answer: "Choose an option below to contact our customer care officer.",
	},
	// Subcategories -> Amenities & Facilities
	{
		index: 7,
		type: responseType.Question,
		question: "Charging Port",
		response: [39, 40],
		answer: "",
	},
	{
		index: 8,
		type: responseType.Question,
		question: "WiFi",
		response: [41, 42, 43, 44],
		answer: "",
	},
	{
		index: 9,
		type: responseType.Question,
		question: "Aircon",
		response: [45],
		answer: "",
	},
	{
		index: 10,
		type: responseType.Question,
		question: "Toilet",
		response: [46],
		answer: "",
	},
	{
		index: 11,
		type: responseType.Question,
		question: "Cables",
		response: [47, 48, 40],
		answer: "",
	},
	{
		index: 12,
		type: responseType.Question,
		question: "Meeting/Discussion Rooms",
		response: [49, 50, 51, 52, 53, 54, 55],
		answer: "",
	},
	{
		index: 13,
		type: responseType.Question,
		question: "Lockers",
		response: [60, 61],
		answer: "",
	},
	{
		index: 14,
		type: responseType.Question,
		question: "Printing",
		response: [62, 63, 64, 65, 66],
		answer: "",
	},
	{
		index: 15,
		type: responseType.Question,
		question: "Height Adjustable Tables",
		response: [67],
		answer: "",
	},
	{
		index: 16,
		type: responseType.Question,
		question: "Pantry",
		response: [68, 69, 70],
		answer: "",
	},
	// Subcategories -> Booking
	{
		index: 17,
		type: responseType.Question,
		question: "Reserving a Seat",
		response: [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
		answer: "",
	},
	{
		index: 18,
		type: responseType.Question,
		question: "Discounts",
		response: [86, 87, 88, 89, 90],
		answer: "",
	},
	{
		index: 19,
		type: responseType.Question,
		question: "Changes or Cancellations",
		response: [91, 92, 93],
		answer: "",
	},
	{
		index: 20,
		type: responseType.Question,
		question: "Package",
		response: [94, 95, 96, 97, 98, 99, 100, 101, 102],
		answer: "",
	},
	{
		index: 21,
		type: responseType.Question,
		question: "Payment Methods",
		response: [103, 104, 105],
		answer: "",
	},
	// Subcategories -> Technical Support
	{
		index: 22,
		type: responseType.Question,
		question: "Aircon",
		response: [106, 107, 108, 109, 110],
		answer: "",
	},
	{
		index: 23,
		type: responseType.Question,
		question: "Connectivity & Network",
		response: [42, 44, 111, 112],
		answer: "",
	},
	{
		index: 24,
		type: responseType.Question,
		question: "Monitors",
		response: [113, 114, 115, 116],
		answer: "",
	},
	{
		index: 25,
		type: responseType.Question,
		question: "Entry",
		response: [117, 118, 119],
		answer: "",
	},
	{
		index: 26,
		type: responseType.Question,
		question: "Printer",
		response: [120, 121, 122, 123, 66],
		answer: "",
	},
	{
		index: 27,
		type: responseType.Question,
		question: "Complains",
		response: [124, 125, 126, 118, 119, 122, 123, 127],
		answer: "",
	},
	{
		index: 28,
		type: responseType.Question,
		question: "Pantry",
		response: [128, 129, 130],
		answer: "",
	},
	// Subcategories -> Co-Teaching
	{
		index: 30,
		type: responseType.Question,
		question: "Teaching @ Spatial",
		response: [],
		answer: "",
	},
	{
		index: 31,
		type: responseType.Question,
		question: "Amenities",
		response: [],
		answer: "",
	},
	{
		index: 32,
		type: responseType.Question,
		question: "Facilities",
		response: [],
		answer: "",
	},
	// Subcategories -> General Information
	{
		index: 33,
		type: responseType.Question,
		question: "Capacity",
		response: [],
		answer: "",
	},
	{
		index: 34,
		type: responseType.Question,
		question: "Operating Hours",
		response: [],
		answer: "",
	},
	{
		index: 35,
		type: responseType.Question,
		question: "Location",
		response: [],
		answer: "",
	},
	{
		index: 36,
		type: responseType.Question,
		question: "Meals Away From Spatial",
		response: [],
		answer: "",
	},
	// Subcategories -> Package
	{
		index: 37,
		type: responseType.Question,
		question: "Purchasing a Package",
		response: [],
		answer: "",
	},
	{
		index: 38,
		type: responseType.Question,
		question: "Terms & Conditions",
		response: [],
		answer: "",
	},
	// Subcategories -> Contact Us
	{
		index: 82,
		type: responseType.Question,
		question: "Telegram",
		response: [],
		answer: "",
	},
	{
		index: 83,
		type: responseType.Question,
		question: "WhatsApp",
		response: [],
		answer: "",
	},
	{
		index: 84,
		type: responseType.Question,
		question: "Call",
		response: [],
		answer: "",
	},
	{
		index: 85,
		type: responseType.Question,
		question: "Email",
		response: [],
		answer: "",
	},
	// Questions
	{
		index: 39,
		type: responseType.Question,
		question: "Can I charge my device at your space?",
		response: [],
		answer: "Yes! There are 4 power points on each seat.",
	},
	{
		index: 40,
		type: responseType.Question,
		question: "Do you have charging cable?",
		response: [],
		answer: "Sorry! We do not provide any charging cables.",
	},
	{
		index: 41,
		type: responseType.Question,
		question: "Is there WiFi?",
		response: [],
		answer: "Yes! We have complimentary WiFi coverage in all our premises for our users.",
	},
	{
		index: 42,
		type: responseType.Question,
		question: "Do I have to pay for WiFi?",
		response: [],
		answer: "No! We have complimentary WiFi coverage in all our premises for our users.",
	},
	{
		index: 43,
		type: responseType.Question,
		question: "Who is your internet service provider?",
		response: [],
		answer: "We are on Starhub Commercial Broadband at 100mbps.",
	},
	{
		index: 44,
		type: responseType.Question,
		question: "What is your WiFi password?",
		response: [],
		answer: "Our WiFi password for\n\n// Spatial Hougang\nSpatial-level-1: yourspaceyourway1\nSpatial-level-2: yourspaceyourway2\n\n// Spatial Toa Payoh\nSpatial-TPY: yourspaceyourway\n\n// Spatial Jurong East\nSpatial-JE: yourspaceyourway",
	},
	{
		index: 45,
		type: responseType.Question,
		question: "Is there aircon?",
		response: [],
		answer: "Yup all Spatial outlets are fully conditioned. We understand the need for aircon to stay productive in Singapore sweltering weather.",
	},
	{
		index: 46,
		type: responseType.Question,
		question: "Where is the toilet?",
		response: [],
		answer: "The toilets at Hougang and Jurong East are located outside of Spatial and within the mall, while the toilet at Toa Payoh is within Spatial.",
	},
	{
		index: 47,
		type: responseType.Question,
		question: "Do you have HDMI cables?",
		response: [],
		answer: "A HDMI cable is provided for every monitor and TV at Spatial. We seek your cooperation to ensure that they remain in working condition for the next user.",
	},
	{
		index: 48,
		type: responseType.Question,
		question: "Do you have Type-C cables/adapters?",
		response: [],
		answer: "We do not provide any Type-C cable or HDMI to Type-C adaptors.",
	},
	{
		index: 49,
		type: responseType.Question,
		question: "Can i hold virtual meeting/zoom at your space?",
		response: [],
		answer: "Yes! Feel free to hold virtual meeting/zoom calls at our space but do be considerate of your volume level and ensure that you are plugged in or connected to your headphones to ensure minimal disruption to other users.",
	},
	{
		index: 50,
		type: responseType.Question,
		question: "Can i talk at your space?",
		response: [],
		answer: "Yes! Feel free to have light conversations at our space but do be considerate of your volume level.",
	},
	{
		index: 51,
		type: responseType.Question,
		question: "Can i take phone calls at your space?",
		response: [],
		answer: "Yes! Feel free to take phone calls at our space but do be considerate of your volume level.",
	},
	{
		index: 52,
		type: responseType.Question,
		question: "Can i hold meetings at your place?",
		response: [],
		answer: "Yes, feel free to hold your meetings here at our space but do be considerate of your volume level to ensure minimal disruption to other users that are hustling too!",
	},
	{
		index: 53,
		type: responseType.Question,
		question: "Can i talk loudly at your space?",
		response: [],
		answer: "No, talking loudly is strictly discouraged unless there are no other users/patrons at the space. If required, you can leave the space to talk loudly before returning to your workspace.",
	},
	{
		index: 54,
		type: responseType.Question,
		question: "Is your space soundproof?",
		response: [],
		answer: "Our meeting rooms have soundproofing boards or are enclosed. But still, we encourage users to be considerate of the space and any conversational volume level is acceptable at Spatial.",
	},
	{
		index: 55,
		type: responseType.Question,
		question: "Can I view your space?",
		response: [56, 57, 58],
		answer: "Please select a location.",
	},
	{
		index: 56,
		type: responseType.Image,
		question: "Spatial @ Hougang",
		response: [59],
		answer: "https://spatial.sg/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fseat-hg.969e5aca.png&w=1920&q=75",
	},
	{
		index: 57,
		type: responseType.Image,
		question: "Spatial @ Toa Payoh",
		response: [59],
		answer: "https://spatial.sg/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fseat-tpy.40fad6ec.png&w=1920&q=75",
	},
	{
		index: 58,
		type: responseType.Image,
		question: "Spatial @ Jurong East",
		response: [59],
		answer: "https://spatial.sg/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fseat-je.95663c2f.png&w=1920&q=75",
	},
	{
		index: 59,
		type: responseType.Question,
		question: "Find out more",
		response: [],
		answer: "Check out our photo gallery of the space at Spatial: https://spatial.sg/. Still not satisfied? Please drop us a text (http://wa.me/6580116004) for your requirements and to arrange a viewing of the space, subject to availability.",
	},
	{
		index: 60,
		type: responseType.Question,
		question: "Can i use the locker?",
		response: [],
		answer: "Go ahead! Lockers are available for use during your booking duration, subjected to availability. Any items should not be left overnight in the lockers. If you want to rent a locker for long term use, the rates are $30/month. Do drop us a text (http://wa.me/6580116004) to rent a locker.",
	},
	{
		index: 61,
		type: responseType.Question,
		question: "Can i use the locker overnight?",
		response: [],
		answer: "Any items should not be left overnight in the lockers. Lockers will be cleared overnight. If you want to rent a locker for long term use, the rates are $30/month. Do drop us a text (http://wa.me/6580116004) to rent a locker.",
	},
	{
		index: 62,
		type: responseType.Question,
		question: "How much do I have to pay for printing?",
		response: [],
		answer: "We offer complimentary printing up to 10 pages Black & White per booking per day. Subsequent pages are chargeable:\n\nBlack & White: $0.03/page\nColoured: $0.45/page\n\nPlease pay to our SGQR located near the printer :D",
	},
	{
		index: 63,
		type: responseType.Question,
		question: "Can I print with colour?",
		response: [],
		answer: "Coloured pages are chargeable at $0.45/page. But do consider the environment before printing :D",
	},
	{
		index: 64,
		type: responseType.Question,
		question: "Can I print double sided?",
		response: [],
		answer: "There are instructions located at the printer section to advise you on how to print double-sided with the Spatial printer.",
	},
	{
		index: 65,
		type: responseType.Question,
		question: "Can I photocopy?",
		response: [],
		answer: "We offer complimentary printing up to 10 pages only for Black & White per booking per day - inclusive of photocopies. But do consider the environment before printing.",
	},
	{
		index: 66,
		type: responseType.Question,
		question: "Can I print via Wi-Fi?",
		response: [],
		answer: "Wi-Fi printing is not advisable due to compatibility issue with various devices. Direct connection via the USB connector cable is preferred. But if you insist, do follow the instructions located on the printer. Don't get frustrated if it dosen't work :P",
	},
	{
		index: 67,
		type: responseType.Question,
		question: "Do you have height adjustable tables?",
		response: [],
		answer: "Yes! Sometimes you're better off standing. We do have height adjustable tables for those who find working/studying while standing more productive!\n\nFor Spatial: Hougang, only seats S03 and S04 have height adjustable tables.\nFor Spatial: Toa Payoh, all S series have are height adjustable tables.\nFor Spatial: Jurong East, all tables except for the D seats are height ajustable tables, even the couple seats! - dont fight yah!",
	},
	{
		index: 68,
		type: responseType.Question,
		question: "What free snacks/drinks do you offer?",
		response: [],
		answer: "We provide little snacks like mamee, chocoroll and some of your childhood favourites. We also provide packet drinks and we have coffee machines. But... since they are complimentary, its while stock last. We will refill them at the end of the day when the paiseh piece is taken :)",
	},
	{
		index: 69,
		type: responseType.Question,
		question: "What premium snacks/drinks do you have?",
		response: [],
		answer: "Premium snacks and drinks are affordable, from $2. Read the labels for exact cost and pay through the SGQR located nearby.",
	},
	{
		index: 70,
		type: responseType.Question,
		question: "How do i pay for the premium snacks/drinks?",
		response: [],
		answer: "Please scan the SGQR code available at the pantry and make payment before consuming your premium snack or drink.",
	},
	{
		index: 71,
		type: responseType.Question,
		question: "How do I make a booking?",
		response: [],
		answer: "You can make your booking at https://spatial.sg/booking",
	},
	{
		index: 72,
		type: responseType.Question,
		question: "What are your rates?",
		response: [],
		answer: "For students refer to this link: https://spatial.sg/costudy\nFor working adults, refer to this link: https://spatial.sg/cowork",
	},
	{
		index: 73,
		type: responseType.Question,
		question: "How long is a half/full day?",
		response: [],
		answer: "Half a day is any 6 consecutive hours. Full day is any 12 consecutive hours. Splitting hours is not allowed.",
	},
	{
		index: 74,
		type: responseType.Question,
		question: "Can I split a half/full day pass?",
		response: [],
		answer: "No, you cannot split a half/full day pass. You must utilise the full 6/12 hours in one go.",
	},
	{
		index: 75,
		type: responseType.Question,
		question:
			"I am booking for one adult and one student, but I cannot select the option.",
		response: [],
		answer: "Unfortunately, you would have to make two seperate bookings for now. One for the adult and one for the student to enjoy the student pricing.",
	},
	{
		index: 76,
		type: responseType.Question,
		question: "Can i extend my booking?",
		response: [],
		answer: "Yes, do make another booking at https://spatial.sg/booking to extend your slot.",
	},
	{
		index: 77,
		type: responseType.Question,
		question: "Can I walk in?",
		response: [],
		answer: "Walk-ins are available. But because we are fully automated, you'd be refered to our website at spatial.sg/booking at our doorstep to walk-in.",
	},
	{
		index: 78,
		type: responseType.Question,
		question:
			"I cannot finish my half day pass / full day, can I carry over to another day?",
		response: [],
		answer: "No, any unused remaining hours in your half and full day passes will not be carried over to other days. Just hustle more yahh!",
	},
	{
		index: 79,
		type: responseType.Question,
		question: "Must I make a booking?",
		response: [],
		answer: "All our seats are reserved to avoid dissapointment. We don't want you to waste a trip because time is previous. Walk-ins are available. But because we are fully automated, you'd be refered to our website at spatial.sg/booking at our doorstep to walk-in.",
	},
	{
		index: 80,
		type: responseType.Question,
		question: "Can i bring my own food and drinks?",
		response: [],
		answer: "Yes, feel free to bring in your own bubble tea and food etc. Just bear in mind to be considerate in the food and drinks that you bring in (like dont bring in durian ok!)",
	},
	{
		index: 86,
		type: responseType.Question,
		question: "How do I qualify for student rates?",
		response: [],
		answer: "Simply make a booking using your educational institution's email address (e.g @abc.edu.sg) to enjoy student rates and discounts.",
	},
	{
		index: 87,
		type: responseType.Question,
		question:
			"I am doing my skillsfuture course, can I qualify for student rate?",
		response: [],
		answer: "No, you would not qualify for student rates, Myskillsfuture courses are for mainly for working adults and thus student rates would not apply.",
	},
	{
		index: 88,
		type: responseType.Question,
		question: "Are there any discount or promocodes?",
		response: [],
		answer: "Stay tuned and follow our Instagram @spatialcollectivesg, TikTok @spatialcollective and Telegram Channel @spatial_spaces to get the latest updates on discount and promo codes.",
	},
	{
		index: 89,
		type: responseType.Question,
		question:
			"Do i get discount if i book your space for an extended duration (one day)?",
		response: [],
		answer: "For extended duration, our discounts for half day (6 hours) and full day (12 hours) passes are already factored in automatically on the booking portal.",
	},
	{
		index: 90,
		type: responseType.Question,
		question: "Is there discount for long-term booking (>3 months)",
		response: [],
		answer: "Please contact us (http://wa.me/6580116004) and we would be happy to quote you competitively!",
	},
	{
		index: 91,
		type: responseType.Question,
		question: "Can i change my seat?",
		response: [],
		answer: "For any changes, please refer to this link: https://spatial.sg/editbooking Do take note of our cancellation and changes policies. Same day changes or cancellations are not allowed. But if you see that the seat is free, please hop onto it.",
	},
	{
		index: 92,
		type: responseType.Question,
		question: "Can i change or cancel my booking?",
		response: [],
		answer: "For any changes, please refer to this link: https://spatial.sg/editbooking Do take note of our cancellation and changes policies. Same day changes or cancellations are not allowed.",
	},
	{
		index: 93,
		type: responseType.Question,
		question: "Will I get a full refund if I cancel my booking?",
		response: [],
		answer: "Please refer to this link: https://spatial.sg/editbooking Do take note of our cancellation and changes policies.",
	},
	{
		index: 94,
		type: responseType.Question,
		question: "How do I purchase a package?",
		response: [],
		answer: "Click on the following link:\nhttps://spatial.sg/costudy > Packages > BUY NOW",
	},
	{
		index: 95,
		type: responseType.Question,
		question: "Can I share a package with my friend?",
		response: [],
		answer: "Yes, you may share the package with your friend. Your friend must use the same email address and contact number that you provided in the purchase.",
	},
	{
		index: 96,
		type: responseType.Question,
		question: "What is the validity of the package?",
		response: [],
		answer: "It is valid 30 days from the intended start date you have indicated in the form.",
	},
	{
		index: 97,
		type: responseType.Question,
		question: "How does a package work?",
		response: [],
		answer: "A unique promocode will be issued to you via a confirmation. Make a booking with the promocode and the amount payable would be zerorised.",
	},
	{
		index: 98,
		type: responseType.Question,
		question: "How does the complimentary hours work?",
		response: [],
		answer: "Simply select an hour of booking and apply the complimentary hour promo codes. i.e. to book for 4 complimentary hours in a row, you would have to make 4 seperate bookings at https://spatial.sg/booking",
	},
	{
		index: 99,
		type: responseType.Question,
		question: "Can I extend beyond 30 days for my package?",
		response: [],
		answer: "No, any extension of packages are subjected to certain conditions on a case by case basis - so come out with a convicing story yep!",
	},
	{
		index: 100,
		type: responseType.Question,
		question: "What happens if I cannot finish my credits within 30 days?",
		response: [],
		answer: "The remaining credits will be forfeitted after the 30 days.",
	},
	{
		index: 101,
		type: responseType.Question,
		question: "Can I refund my unused credits?",
		response: [],
		answer: "There will be no refunds for any unused credits after purchasing a package.",
	},
	{
		index: 102,
		type: responseType.Question,
		question:
			"I bought a new package before my current one expires, when does my package end?",
		response: [],
		answer: "We will take the later of the 2 expiry dates - all reamining credits will automatically be extended.",
	},
	{
		index: 103,
		type: responseType.Question,
		question: "Do you accept cash?",
		response: [],
		answer: "We are cashless! As we transit towards a more digital and cashless society, our only form of payment is via digital payment using PayNow/SGQR",
	},
	{
		index: 104,
		type: responseType.Question,
		question: "What are they payment methods you accept?",
		response: [],
		answer: "We are cashless! As we transit towards a more digital and cashless society, our only form of payment is via digital payment using PayNow/SGQR",
	},
	{
		index: 105,
		type: responseType.Question,
		question: "I do not have paylah/paynow can i pay cash?",
		response: [],
		answer: "Our only form of payment is via digital payment using PayNow. Alternatively, you can try using GrabPay / ShopeePay / GooglePay or directly bank transfer to us. Last resort is to ask your bff to help you pay first :D",
	},
	{
		index: 106,
		type: responseType.Question,
		question: "The aircon is not turned on.",
		response: [],
		answer: "Please do drop us a text (http://wa.me/6580116004) and inform us if the aircon is not turned on.",
	},
	{
		index: 107,
		type: responseType.Question,
		question: "The aircon is not cold.",
		response: [],
		answer: "Please do drop us a text (http://wa.me/6580116004) and inform us if the aircon is not cold.",
	},
	{
		index: 108,
		type: responseType.Question,
		question: "The aircon is too cold.",
		response: [],
		answer: "Please do drop us a text (http://wa.me/6580116004) and inform us if the aircon is too cold.",
	},
	{
		index: 109,
		type: responseType.Question,
		question: "Where is the remote control for the aircon?",
		response: [],
		answer: "There's no remote because we control the remotes remotely! Please do drop us a text (http://wa.me/6580116004) and let us know what we can do for you for the aircon.",
	},
	{
		index: 110,
		type: responseType.Question,
		question: "Can i change the temperature of the aircon?",
		response: [],
		answer: "Please do drop us a text (http://wa.me/6580116004) and let us know what we can do for you for the aircon.",
	},
	{
		index: 111,
		type: responseType.Question,
		question: "I am unable to connect to your Wi-Fi.",
		response: [],
		answer: "Please check if you have entered the correct password and do try reconnecting to the Wi-Fi. If the issues still persist, please drop us a text (http://wa.me/6580116004) and our customer service officers will assist your further. Our WiFi password for\n\n// Spatial Hougang\nSpatial-level-1: yourspaceyourway1\nSpatial-level-2: yourspaceyourway2\n\n// Spatial Toa Payoh\nSpatial-TPY: yourspaceyourway\n\n// Spatial Jurong East\nSpatial-JE: yourspaceyourway",
	},
	{
		index: 112,
		type: responseType.Question,
		question: "Your network speed is slow and lagging.",
		response: [],
		answer: "Sorry to hear that! Must be the usual breakdown by Starhub again. We will try to help by resetting the network - it works sometimes. Drop us a text (http://wa.me/6580116004) and our customer service officers will assist your further.",
	},
	{
		index: 113,
		type: responseType.Question,
		question: "How do I turn on the monitor?",
		response: [],
		answer: "There is a button located either below the brand logo or on the back of the monitor. Please do also check your HDMI connection and that the power switch for the monitor is turned on.",
	},
	{
		index: 114,
		type: responseType.Question,
		question: "The TV cannot be turned on.",
		response: [],
		answer: "There is remote control for each TV and will be found in the container box below or beside TV. Please do also check your HDMI connection and that the power switch for the TV is turned on.",
	},
	{
		index: 115,
		type: responseType.Question,
		question: "The monitor cannot be turned on.",
		response: [],
		answer: "There is either a button located below the brand logo or on the back of the monitor. Please do also check your HDMI connection and that the power switch for the monitor is turned on.",
	},
	{
		index: 116,
		type: responseType.Question,
		question: "There is no connection.",
		response: [],
		answer: "There is either a button located below the brand logo or on the back of the monitor. Please do also check your HDMI connection and that the power switch for the monitor is turned on.",
	},
	{
		index: 117,
		type: responseType.Question,
		question: "How do i enter your space?",
		response: [],
		answer: 'You may enter Spatial 15 minutes before the start of your booking time.\nGetting into Spatial is simple, there are 3 ways to unlock the door.\n\n(1) Contactless via email\n- Click on the "click here" button in your confirmation email\n- Pull and enter\n\n(2) Contactless via QR Code\n- Scan the QR code on the glass door\n- Enter your access code (6 digits from confirmation email)\n\n(3) Touchpad (please be patient!)\n- Press "Card" on door lock to wake the lock up, wait 2 seconds for the number pad to be lit\n- Enter your Access Code followed by the "#" key\n\nIf you are entering Spatial via a third party application - please text us! (http://wa.me/6580116004)\n\nIf these methods still do not work, feel free to drop us a text (http://wa.me/6580116004) for assistance.',
	},
	{
		index: 118,
		type: responseType.Question,
		question: "The keypad is not working.",
		response: [],
		answer: "Please be patient with the keypad and enter your access code slowly into the keypad. Alternatively, you can scan the entry QR code and type in your booking reference.",
	},
	{
		index: 119,
		type: responseType.Question,
		question: "I did not receive the confirmation email.",
		response: [],
		answer: "Please check your inbox/spam/junk folder first - sometimes the email might be sent there instead. Do drop us a text (http://wa.me/6580116004) if you are still unable to find your confirmation.",
	},
	{
		index: 120,
		type: responseType.Question,
		question: "How do I print?",
		response: [],
		answer: "Fret not, there will instructions located at the printer section to advise you on how to print with the Spatial printer.",
	},
	{
		index: 121,
		type: responseType.Question,
		question: "The paper is jammed.",
		response: [],
		answer: "Self service yah! Please remove any scrapes or pieces of paper stuck in the printer from the feeder tray. But if it is too complex (dont try so hard pls!), please print another day or head to the nearby malls to print if it is super urgent!",
	},
	{
		index: 122,
		type: responseType.Question,
		question: "There is no paper.",
		response: [],
		answer: "We offer complimentary printing up to 10 pages only for Black & White per booking per day. If the printer is out of paper and you need to print urgently, please do find other alternative printing services at the nearby malls. If it is not urgent, our staff will refill the paper at the end of the day, please come again!",
	},
	{
		index: 123,
		type: responseType.Question,
		question: "There is no ink.",
		response: [],
		answer: "We offer complimentary printing. If the printer is out of ink and you need to print urgently, please do find other alternative printing services at the nearby malls. If it is not urgent, our staff will change the toner at the end of the day, please come again! Sometimes, we are also at the mercy of supply chain issues. SORRY!",
	},
	{
		index: 124,
		type: responseType.Question,
		question: "There is someone talking very loudly.",
		response: [],
		answer: "Patrons of Spatial are often considerate and will react kindly if you tell them! Let us know if they don't corporate!",
	},
	{
		index: 125,
		type: responseType.Question,
		question: "I made a booking, but someone is at my seat.",
		response: [],
		answer: "Please check if you are at the correct seat and have arrived at your timing. If yes, gently remind the previous customer that you have made a booking - they quite automatic one. Please do drop us a text (http://wa.me/6580116004) if you require further assistance.",
	},
	{
		index: 126,
		type: responseType.Question,
		question: "The toilet has no toilet paper.",
		response: [],
		answer: "Someone had a bad stomach day! Got your own tissue paper or use the bidet? The toilet paper will be refilled at the end of the day. Sorry for the inconvenience.",
	},
	{
		index: 127,
		type: responseType.Question,
		question: "The table/floor is dirty",
		response: [],
		answer: "We are so sorry about the that. Need to dock the salary of our robot cleaners already! Do drop us a text (http://wa.me/6580116004) if you are more suggestions / feedbacks",
	},
	{
		index: 128,
		type: responseType.Question,
		question: "The coffee machine says to empty coffee grounds.",
		response: [],
		answer: "To fix:\n1. Gently pull out the drip tray and hold on to it.\n2. Remove the little container from the drip tray.\n3. Dump the coffee grounds into the trash bin beside the coffee machine.\n4. Do hold on to the coffee ground containers and do not throw it away.\n5. Place the container back onto the drip tray and reinsert it into the machine.\n6. Repeat Step 5 if error still exists - the coffee machine should be good to go.\nPLEASE DON'T THROW THE CONTAINER AWAY!!!",
	},
	{
		index: 129,
		type: responseType.Question,
		question: "The snacks ran out, can you refill it?",
		response: [],
		answer: "Apologies that we have ran out of snacks, our snacks will be refilled at the end of the day. Come earlier tomorrow okay!",
	},
	{
		index: 130,
		type: responseType.Question,
		question: "The drinks ran out, can you refill it?",
		response: [],
		answer: "Apologies that we have ran out of drinks, our drinks will be refilled at the end of the day. Come earlier tomorrow okay!",
	},
];

/**
 * Last Used Index: 
 * 
 * Template:
 * 	{
		index: 0,
		type: responseType.Question,
		question: "",
		response: [],
		answer: "",
	},
 * 
 */
