export const responseType = {
	Question: "q",
	Image: "i",
};

export const questions = [
	{
		index: 0,
		type: responseType.Question,
		question: "FAQ",
		response: [1, 2, 3, 4, 5, 6],
		answer: "Have a question? Search for the answer in the categories below. If you do not find the answer to your question, please message us at http://wa.me/6580116004",
	},
	// Categories
	{
		index: 1,
		type: responseType.Question,
		question: "Amenities & Facilities",
		response: [7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
		answer: "",
	},
	{
		index: 2,
		type: responseType.Question,
		question: "Booking",
		response: [17, 18, 19, 20, 21],
		answer: "",
	},
	{
		index: 3,
		type: responseType.Question,
		question: "Technical Support",
		response: [22, 23, 24, 25, 26, 27, 28, 29],
		answer: "",
	},
	{
		index: 4,
		type: responseType.Question,
		question: "Co-Teaching",
		response: [30, 31, 32],
		answer: "",
	},
	{
		index: 5,
		type: responseType.Question,
		question: "General Information",
		response: [33, 34, 35, 36],
		answer: "",
	},
	{
		index: 6,
		type: responseType.Question,
		question: "Package",
		response: [37, 38],
		answer: "",
	},
	// Subcategories -> Amenities & Facilities
	{
		index: 7,
		type: responseType.Question,
		question: "Charging Port",
		response: [39, 40],
		answer: "",
	},
	{
		index: 8,
		type: responseType.Question,
		question: "WiFi",
		response: [41, 42, 43, 44],
		answer: "",
	},
	{
		index: 9,
		type: responseType.Question,
		question: "Aircon",
		response: [45],
		answer: "",
	},
	{
		index: 10,
		type: responseType.Question,
		question: "Toilet",
		response: [46],
		answer: "",
	},
	{
		index: 11,
		type: responseType.Question,
		question: "Cables",
		response: [47, 48, 40],
		answer: "",
	},
	{
		index: 12,
		type: responseType.Question,
		question: "Meeting/Discussion Rooms",
		response: [49, 50, 51, 52, 53, 54, 55],
		answer: "",
	},
	{
		index: 13,
		type: responseType.Question,
		question: "Lockers",
		response: [60, 61],
		answer: "",
	},
	{
		index: 14,
		type: responseType.Question,
		question: "Printing",
		response: [62, 63, 64, 65, 66],
		answer: "",
	},
	{
		index: 15,
		type: responseType.Question,
		question: "Height Adjustable Tables",
		response: [67],
		answer: "",
	},
	{
		index: 16,
		type: responseType.Question,
		question: "Pantry",
		response: [],
		answer: "",
	},
	// Subcategories -> Booking
	{
		index: 17,
		type: responseType.Question,
		question: "Reserving a Seat",
		response: [],
		answer: "",
	},
	{
		index: 18,
		type: responseType.Question,
		question: "Discounts",
		response: [],
		answer: "",
	},
	{
		index: 19,
		type: responseType.Question,
		question: "Changes or Cancellations",
		response: [],
		answer: "",
	},
	{
		index: 20,
		type: responseType.Question,
		question: "Package",
		response: [],
		answer: "",
	},
	{
		index: 21,
		type: responseType.Question,
		question: "Payment Methods",
		response: [],
		answer: "",
	},
	// Subcategories -> Technical Support
	{
		index: 22,
		type: responseType.Question,
		question: "Aircon",
		response: [],
		answer: "",
	},
	{
		index: 23,
		type: responseType.Question,
		question: "Connectivity & Network",
		response: [],
		answer: "",
	},
	{
		index: 24,
		type: responseType.Question,
		question: "Monitors",
		response: [],
		answer: "",
	},
	{
		index: 25,
		type: responseType.Question,
		question: "Entry",
		response: [],
		answer: "",
	},
	{
		index: 26,
		type: responseType.Question,
		question: "Printer",
		response: [],
		answer: "",
	},
	{
		index: 27,
		type: responseType.Question,
		question: "Complains",
		response: [],
		answer: "",
	},
	{
		index: 28,
		type: responseType.Question,
		question: "Pantry",
		response: [],
		answer: "",
	},
	{
		index: 29,
		type: responseType.Question,
		question: "Toilet",
		response: [],
		answer: "",
	},
	// Subcategories -> Co-Teaching
	{
		index: 30,
		type: responseType.Question,
		question: "Teaching @ Spatial",
		response: [],
		answer: "",
	},
	{
		index: 31,
		type: responseType.Question,
		question: "Amenities",
		response: [],
		answer: "",
	},
	{
		index: 32,
		type: responseType.Question,
		question: "Facilities",
		response: [],
		answer: "",
	},
	// Subcategories -> General Information
	{
		index: 33,
		type: responseType.Question,
		question: "Capacity",
		response: [],
		answer: "",
	},
	{
		index: 34,
		type: responseType.Question,
		question: "Operating Hours",
		response: [],
		answer: "",
	},
	{
		index: 35,
		type: responseType.Question,
		question: "Location",
		response: [],
		answer: "",
	},
	{
		index: 36,
		type: responseType.Question,
		question: "Meals Away From Spatial",
		response: [],
		answer: "",
	},
	// Subcategories -> Package
	{
		index: 37,
		type: responseType.Question,
		question: "Purchasing a Package",
		response: [],
		answer: "",
	},
	{
		index: 38,
		type: responseType.Question,
		question: "Terms & Conditions",
		response: [],
		answer: "",
	},
	// Questions
	{
		index: 39,
		type: responseType.Question,
		question: "Can I charge my device at your space?",
		response: [],
		answer: "Yes! There are 4 power points on each seat.",
	},
	{
		index: 40,
		type: responseType.Question,
		question: "Do you have charging cable?",
		response: [],
		answer: "Sorry! We do not provide any charging cables.",
	},
	{
		index: 41,
		type: responseType.Question,
		question: "Is there WiFi?",
		response: [],
		answer: "Yes! We have complimentary WiFi coverage in all our premises for our users.",
	},
	{
		index: 42,
		type: responseType.Question,
		question: "Do I have to pay for WiFi?",
		response: [],
		answer: "No! We have complimentary WiFi coverage in all our premises for our users.",
	},
	{
		index: 43,
		type: responseType.Question,
		question: "Who is your internet service provider?",
		response: [],
		answer: "We are on Starhub Commercial Broadband at 100mbps.",
	},
	{
		index: 44,
		type: responseType.Question,
		question: "What is your WiFi password?",
		response: [],
		answer: "Our WiFi password for\n\n// Spatial Hougang\nSpatial-level-1: yourspaceyourway1\nSpatial-level-2: yourspaceyourway2\n\n// Spatial Toa Payoh\nSpatial-TPY: yourspaceyourway\n\n// Spatial Jurong East\nSpatial-JE: yourspaceyourway",
	},
	{
		index: 45,
		type: responseType.Question,
		question: "Is there aircon?",
		response: [],
		answer: "Yup all Spatial outlets are fully conditioned. We understand the need for aircon to stay productive in Singapore sweltering weather.",
	},
	{
		index: 46,
		type: responseType.Question,
		question: "Where is the toilet?",
		response: [],
		answer: "The toilets at Hougang and Jurong East are located outside of Spatial and within the mall, while the toilet at Toa Payoh is within Spatial.",
	},
	{
		index: 47,
		type: responseType.Question,
		question: "Do you have HDMI cables?",
		response: [],
		answer: "A HDMI cable is provided for every monitor and TV at Spatial. We seek your cooperation to ensure that they remain in working condition for the next user.",
	},
	{
		index: 48,
		type: responseType.Question,
		question: "Do you have Type-C cables/adapters?",
		response: [],
		answer: "We do not provide any Type-C cable or HDMI to Type-C adaptors.",
	},
	{
		index: 49,
		type: responseType.Question,
		question: "Can i hold virtual meeting/zoom at your space?",
		response: [],
		answer: "Yes! Feel free to hold virtual meeting/zoom calls at our space but do be considerate of your volume level and ensure that you are plugged in or connected to your headphones to ensure minimal disruption to other users.",
	},
	{
		index: 50,
		type: responseType.Question,
		question: "Can i talk at your space?",
		response: [],
		answer: "Yes! Feel free to have light conversations at our space but do be considerate of your volume level.",
	},
	{
		index: 51,
		type: responseType.Question,
		question: "Can i take phone calls at your space?",
		response: [],
		answer: "Yes! Feel free to take phone calls at our space but do be considerate of your volume level.",
	},
	{
		index: 52,
		type: responseType.Question,
		question: "Can i hold meetings at your place?",
		response: [],
		answer: "Yes, feel free to hold your meetings here at our space but do be considerate of your volume level to ensure minimal disruption to other users that are hustling too!",
	},
	{
		index: 53,
		type: responseType.Question,
		question: "Can i talk loudly at your space?",
		response: [],
		answer: "No, talking loudly is strictly discouraged unless there are no other users/patrons at the space. If required, you can leave the space to talk loudly before returning to your workspace.",
	},
	{
		index: 54,
		type: responseType.Question,
		question: "Is your space soundproof?",
		response: [],
		answer: "Our meeting rooms have soundproofing boards or are enclosed. But still, we encourage users to be considerate of the space and any conversational volume level is acceptable at Spatial.",
	},
	{
		index: 55,
		type: responseType.Question,
		question: "Can I view your space?",
		response: [56, 57, 58],
		answer: "Please select a location.",
	},
	{
		index: 56,
		type: responseType.Image,
		question: "Spatial @ Hougang",
		response: [59],
		answer: "https://spatial.sg/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fseat-hg.969e5aca.png&w=1920&q=75",
	},
	{
		index: 57,
		type: responseType.Image,
		question: "Spatial @ Toa Payoh",
		response: [59],
		answer: "https://spatial.sg/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fseat-tpy.40fad6ec.png&w=1920&q=75",
	},
	{
		index: 58,
		type: responseType.Image,
		question: "Spatial @ Jurong East",
		response: [59],
		answer: "https://spatial.sg/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fseat-je.95663c2f.png&w=1920&q=75",
	},
	{
		index: 59,
		type: responseType.Question,
		question: "Find out more",
		response: [],
		answer: "Check out our photo gallery of the space at Spatial: https://spatial.sg/. Still not satisfied? Please drop us a text (http://wa.me/6580116004) for your requirements and to arrange a viewing of the space, subject to availability.",
	},
	{
		index: 60,
		type: responseType.Question,
		question: "Can i use the locker?",
		response: [],
		answer: "Go ahead! Lockers are available for use during your booking duration, subjected to availability. Any items should not be left overnight in the lockers. If you want to rent a locker for long term use, the rates are $30/month. Do drop us a text (http://wa.me/6580116004) to rent a locker.",
	},
	{
		index: 61,
		type: responseType.Question,
		question: "Can i use the locker overnight?",
		response: [],
		answer: "Any items should not be left overnight in the lockers. Lockers will be cleared overnight. If you want to rent a locker for long term use, the rates are $30/month. Do drop us a text (http://wa.me/6580116004) to rent a locker.",
	},
	{
		index: 62,
		type: responseType.Question,
		question: "How much do I have to pay for printing?",
		response: [],
		answer: "We offer complimentary printing up to 10 pages Black & White per booking per day. Subsequent pages are chargeable:\n\nBlack & White: $0.03/page\nColoured: $0.45/page\n\nPlease pay to our SGQR located near the printer :D",
	},
	{
		index: 63,
		type: responseType.Question,
		question: "Can I print with colour?",
		response: [],
		answer: "Coloured pages are chargeable at $0.45/page. But do consider the environment before printing :D",
	},
	{
		index: 64,
		type: responseType.Question,
		question: "Can I print double sided?",
		response: [],
		answer: "There are instructions located at the printer section to advise you on how to print double-sided with the Spatial printer.",
	},
	{
		index: 65,
		type: responseType.Question,
		question: "Can I photocopy?",
		response: [],
		answer: "We offer complimentary printing up to 10 pages only for Black & White per booking per day - inclusive of photocopies. But do consider the environment before printing.",
	},
	{
		index: 66,
		type: responseType.Question,
		question: "Can I print via Wi-Fi?",
		response: [],
		answer: "Wi-Fi printing is not advisable due to compatibility issue with various devices. Direct connection via the USB connector cable is preferred. But if you insist, do follow the instructions located on the printer. Don't get frustrated if it dosen't work :P",
	},
	{
		index: 67,
		type: responseType.Question,
		question: "Do you have height adjustable tables?",
		response: [],
		answer: "Yes! Sometimes you're better off standing. We do have height adjustable tables for those who find working/studying while standing more productive!\n\nFor Spatial: Hougang, only seats S03 and S04 have height adjustable tables.\nFor Spatial: Toa Payoh, all S series have are height adjustable tables.\nFor Spatial: Jurong East, all tables except for the D seats are height ajustable tables, even the couple seats! - dont fight yah!",
	},
];

/**
 * Last Used Index: 
 * 
 * Template:
 * 	{
		index: 0,
		type: responseType.Question,
		question: "",
		response: [],
		answer: "",
	},
 * 
 */
